on: [pull_request]

name: CI-GG

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          DB_CONNECTION: postgres
          DB_HOST: localhost
          DB_PORT: 5433
          DB_USER: postgres
          DB_PASSWORD: docker
          DB_DATABASE: daledb
        ports:
          - '5433:5432'

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.14.2'
          registry-url: 'https://npm.pkg.github.com'
      - name: Installation
        run: yarn
      - name: Lint project
        run: yarn lint:fix
      - name: Test Champions
        run: yarn test:champion
      - name: Test Summoners
        run: yarn test:summoner
      - name: Build
        run: yarn build
        env:
          CI: true
